function(nova_extract_version VERSION_FILE)
    file(READ "${NOVA_VERSION_FILE}" file_contents)
    string(REGEX MATCH ".*NovaVersionMajor = ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract major version number from nova/nova.h")
    endif()
    set(ver_major ${CMAKE_MATCH_1})

    string(REGEX MATCH ".*NovaVersionMinor = ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract minor version number from nova/nova.h")
    endif()

    set(ver_minor ${CMAKE_MATCH_1})
    string(REGEX MATCH ".*NovaVersionPatch = ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract patch version number from nova/nova.h")
    endif()
    set(ver_patch ${CMAKE_MATCH_1})

    set(NOVA_VERSION_MAJOR ${ver_major} PARENT_SCOPE)
    set(NOVA_VERSION_MINOR ${ver_minor} PARENT_SCOPE)
    set(NOVA_VERSION_PATCH ${ver_patch} PARENT_SCOPE)
    set(NOVA_VERSION "${ver_major}.${ver_minor}.${ver_patch}" PARENT_SCOPE)
endfunction()
