name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-24.04, windows-latest ]
        build_type: [ Debug, Release ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: turtlebrowser/get-conan@main
      with:
        version: "2.6.0"
    - name: Install GCC
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Unit Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

    - name: Package
      run: conan create ${{github.workspace}}/build --test-folder package-test --build=missing
