name: Cross platform build and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        build_type: [ Debug, Release ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: turtlebrowser/get-conan@main

    - name: Build
      run: |
        cmake -S ${{github.workspace}}/libnova -B ${{github.workspace}}/build/libnova -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{github.workspace}}/conan_provider.cmake
        cmake --build ${{github.workspace}}/build/libnova

    - name: Unit Test
      working-directory: ${{github.workspace}}/build/libnova
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

    - name: Install
      run: cmake --install ${{github.workspace}}/build/libnova --prefix ${{github.workspace}}/install

    - name: Functional Test
      run: |
        cmake -S ${{github.workspace}}/tests -B ${{github.workspace}}/build/tests -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{github.workspace}}/conan_provider.cmake -DCMAKE_PREFIX_PATH=${{github.workspace}}/install
        cmake --build ${{github.workspace}}/build/tests

    - name: Package
      run: conan create ${{github.workspace}}/libnova --test-folder ${{github.workspace}}/tests/package --build=missing --settings compiler.cppstd=20

    - name: Examples
      run: |
        cmake -S ${{github.workspace}}/examples -B ${{github.workspace}}/build/examples -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=${{github.workspace}}/conan_provider.cmake -DCMAKE_PREFIX_PATH=${{github.workspace}}/install
        cmake --build ${{github.workspace}}/build/examples
